-- ============================================================================
-- Daily Signals Table Schema
-- ============================================================================
-- Stores signals generated by the Daily Scanner (AWS Batch job)
-- Signals are generated by running pre-built strategies on all active symbols
-- ============================================================================

CREATE TABLE IF NOT EXISTS daily_signals (
    symbol VARCHAR(50) NOT NULL,
    date DATE NOT NULL,
    strategy_name VARCHAR(255) NOT NULL,
    signal VARCHAR(10) NOT NULL CHECK (signal IN ('BUY', 'SELL', 'HOLD')),
    price DECIMAL(10,2) NOT NULL,
    confidence DECIMAL(5,4) DEFAULT 0.0 CHECK (confidence >= 0.0 AND confidence <= 1.0),
    setup_valid BOOLEAN DEFAULT FALSE,
    trigger_met BOOLEAN DEFAULT FALSE,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (symbol, date, strategy_name)
);

COMMENT ON TABLE daily_signals IS 'Daily signals generated by strategy scanner (runs after data pipeline)';
COMMENT ON COLUMN daily_signals.symbol IS 'Stock symbol (e.g., AAPL)';
COMMENT ON COLUMN daily_signals.date IS 'Signal date';
COMMENT ON COLUMN daily_signals.strategy_name IS 'Name of the strategy that generated the signal';
COMMENT ON COLUMN daily_signals.signal IS 'Signal type: BUY, SELL, or HOLD';
COMMENT ON COLUMN daily_signals.price IS 'Price at which signal was generated';
COMMENT ON COLUMN daily_signals.confidence IS 'Signal confidence score (0.0 to 1.0)';
COMMENT ON COLUMN daily_signals.setup_valid IS 'Whether setup conditions were met';
COMMENT ON COLUMN daily_signals.trigger_met IS 'Whether trigger conditions were met';
COMMENT ON COLUMN daily_signals.metadata IS 'Additional strategy-specific metadata (JSON)';

-- ============================================================================
-- Indexes for Fast Queries
-- ============================================================================

-- Index for querying signals by symbol and date (most common query)
CREATE INDEX IF NOT EXISTS idx_daily_signals_symbol_date 
ON daily_signals(symbol, date DESC);

-- Index for querying signals by strategy and date (for strategy performance analysis)
CREATE INDEX IF NOT EXISTS idx_daily_signals_strategy_date 
ON daily_signals(strategy_name, date DESC);

-- Index for querying BUY signals (for "Suggested Stocks" dashboard)
CREATE INDEX IF NOT EXISTS idx_daily_signals_buy 
ON daily_signals(date DESC, strategy_name) 
WHERE signal = 'BUY';

-- Index for querying by confidence (for filtering high-confidence signals)
CREATE INDEX IF NOT EXISTS idx_daily_signals_confidence 
ON daily_signals(date DESC, confidence DESC) 
WHERE signal = 'BUY' AND confidence > 0.5;

-- Composite index for common dashboard queries (symbol + strategy + date)
CREATE INDEX IF NOT EXISTS idx_daily_signals_symbol_strategy_date 
ON daily_signals(symbol, strategy_name, date DESC);

-- ============================================================================
-- Retention Policy (Optional - if using TimescaleDB)
-- ============================================================================
-- Uncomment if using TimescaleDB and want automatic data retention
-- SELECT add_retention_policy('daily_signals', INTERVAL '2 years');

-- ============================================================================
-- Sample Queries
-- ============================================================================

-- Get latest signals for a symbol
-- SELECT * FROM daily_signals 
-- WHERE symbol = 'AAPL' 
-- ORDER BY date DESC 
-- LIMIT 10;

-- Get all BUY signals for today
-- SELECT * FROM daily_signals 
-- WHERE date = CURRENT_DATE 
-- AND signal = 'BUY' 
-- ORDER BY confidence DESC;

-- Get signals by strategy
-- SELECT * FROM daily_signals 
-- WHERE strategy_name = 'Golden Cross' 
-- AND date >= CURRENT_DATE - INTERVAL '30 days'
-- ORDER BY date DESC;
